### ISSUE TITLE
Is Dnd5e foundry modules apply same for name generator?

### ISSUE THREAD

**Issue by marcelsgomz** [NateHawk85/Nathans-DnD5e-Foundry-Modules#12]
As I read above this module for math expression calculator and its results are amazing. I wanna ask can we use this as same for [name combiner](https://easynamesgenerator.com/). If yes, what changes will be done for numbers to alphabets changings?

**Comment by sawetra09** [comment]
want to know that can i use this for my AdSense niche [Mepco Online](https://mepcobills.pk/mepco-online-bill-payment/)   which is also a WordPress site
