### ISSUE TITLE
Lichtgeschwindigkeit is no longer needed for V10.

### ISSUE THREAD

**Issue by SirMotte** [NateHawk85/Nathans-DnD5e-Foundry-Modules#15]
![grafik](https://user-images.githubusercontent.com/82598692/191593736-3d8773b5-06c6-4ba5-8a0a-63dde7cb10e5.png)
![grafik](https://user-images.githubusercontent.com/82598692/191593816-176946d3-8743-4afb-b135-91aa0e5760e7.png)

**Comment by NateHawk85** [comment]
Thanks for that! I haven't updated too much recently, but once I migrate to v10, I'll make sure to remove Lichtgeschwindigkeit from the list.

**Comment by SirMotte** [comment]
> Thanks for that! I haven't updated too much recently, but once I migrate to v10, I'll make sure to remove Lichtgeschwindigkeit from the list.

A lot of stuff is broken right know, but I won't report on that yet as it'd be premature to do so. But this is one of the extensions clearly deprecated.

Thank you for this incredible document and all the effort you put in!
Until then.

**Comment by NateHawk85** [comment]
Will be addressed in #16!
