### ISSUE TITLE
Navbar Tweak Scene Name Functionality

### ISSUE THREAD

**Issue by Red5Phil** [NateHawk85/Nathans-DnD5e-Foundry-Modules#6]
I’m trying to figure out whether or not navbar tweaks’ functionality has actually been supplanted, as the guide suggests it has. The main thing I use it for is to keep the actual scene name visible to me while showing the navigation name to my players. Is this functionality present else where or do I still need navbar tweaks in this case?

**Comment by NateHawk85** [comment]
I believe this functionality is already included, whether by core Foundry or another module I have installed, I'm not certain. Here are the options that allow me to control the "player's" view while keeping mine the same:
![Capture](https://user-images.githubusercontent.com/7596412/111925151-a50f9280-8a75-11eb-837c-fceb1e246ee1.PNG)
