### ISSUE TITLE
The Furnace depreciated

### ISSUE THREAD

**Issue by DerHerzog7** [NateHawk85/Nathans-DnD5e-Foundry-Modules#9]
Looks like The Furnace has been depreciated. From FoundryHub:

"An update from the League of Foundry Devs. Kakaroto has left the Furnace in community hands so he can focus on working on the Forge.
With 0.8, several of the Forge’s larger functionalities broke pretty badly.

Some of the things the Forge did was already being replaced by smaller modules so we made the call to continue splitting it up and salvaging what could be saved like that.

An update for 0.8.4 was released which contains no code, but instead is dependent on all of the smaller modules:

Advanced Macros
Initiative Double Click
DFreds Droppables
Less Fog
Split Journal
These cover almost all the functionality that was still working at the end of 0.7."

**Comment by NateHawk85** [comment]
Thanks for the heads up! Personally, I haven't upgraded past 0.7.9 because of module incompatabilities, but I'll keep this in mind for the future. I'll also revaluate whether or not The Furnace is needed for my current configuration.

**Comment by DerHerzog7** [comment]
Yeh I've found that most modules you recommend are now updated. The furnace has some suggestions for replacement modules too. 

I love this list btw. I'm regularly reviewing wha ti have based on your recommendations.

**Comment by NateHawk85** [comment]
It's not reflected here, but in my process to update to 0.8.7, I have removed The Furnace and added those modules for review. Thank you for bringing this up! :)
